### ISSUE TITLE
ask init doesn't create a skill.json file

### ISSUE THREAD

**Issue by abhinavjayanthy** [alexa/ask-cli#284] opened 2020-08-14 13:09 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

When we clone a self provisioned skill, the cli should create a skill.json file. 
## Current Behavior

When we clone a self provisioned skill, the cli doesn't create a skill.json file. If this is not created and a user tries to deploy, the error message is also misleading,

**CLI Snapshot**
The Cli comes back with a warning like,

![Screen Shot 2020-08-17 at 10 28 50 AM](https://user-images.githubusercontent.com/33322133/90408546-f71eae80-e075-11ea-8164-b146456510f3.png)

## Steps to Reproduce (for bugs)

Create a new skill which is self provisioned and then try to clone it locally with ask init, notice that cli doesn't create a skill.json. 
Try to deploy it and cli comes back with a misleading error

## Possible Solution

Create a skill.json or provide an error saying the skill.json is missing. 

## Your Environment and Context

* ask-cli version: 2.14.0
* Operating System and version: Mac os, 10.14.6
* Node.js version used for development: 10.15
* NPM version used for development: 6.14.6

**Comment by kakhaUrigashvili** [comment] 2020-08-16 04:02
@abhinavjayanthy there is already PR to fix misleading error https://github.com/alexa/ask-cli/pull/282

I also remember seeing what you described (not downloading/creating skill.json) before. I was previously told that it was by design. I will double check with the team why it was design this way.

If you have existing skill and you want to download skill package which would include skill.json. You can use the following command.

`rm -rf skill-package; ask smapi export-package -s amzn1.ask.skill.af4c520d-aa37-4ef8-b0f5-8f40659e237f -g development`

**Comment by abhinavjayanthy** [comment] 2020-08-17 14:55
@kakhaUrigashvili I ran the command, it does what is it supposed to do, that is, delete the package and download the new one. After this, I ran ask deploy, here is the command line output, 

![Screen Shot 2020-08-17 at 10 51 21 AM](https://user-images.githubusercontent.com/33322133/90410245-1b7b8a80-e078-11ea-94fa-ceb3e4119210.png)

Notice that it missed the lambda deployment, is this because of the changes I made for the issue #283

**Comment by kakhaUrigashvili** [comment] 2020-08-17 15:59
@abhinavjayanthy yes. After the change you made ask cli only manages skill-package and does not deploy lambda. You actually can also delete "code" property from ask-states.json and ask-resources.json since you dont need cli to create zip of your lambda folder.

**Comment by kakhaUrigashvili** [comment] 2020-09-22 20:04
closing it. the behavior is intended. We put on the backlog to potentially change the behavior.

**Closed by kakhaUrigashvili** 2020-09-22 20:04 UTC
Labels: Status: Wait Response
