### ISSUE TITLE
[Error]: Failed to retrieve the template list, please see the details from the error response.

### ISSUE THREAD

**Issue by rubenturcios** [alexa/ask-cli#428] opened 2022-03-04 20:36 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

When using `ask new` (and `aws new --profile default`) to set up a new Alexa Skill, I receive a 403 error from the AmazonS3 server. 

## Expected Behavior

`ask new` should initialize a new project folder with desired name and required skill folders

## Current Behavior

When using `ask new` (and `aws new --profile default`) to set up a new Alexa Skill, I receive a 403 error from the AmazonS3 static file server after picking the requested run time (fails for any runtime) and picking either AWS with CF or AWS with Lambda

My aws cli is configured correctly as I have been able to make aws cli request with the default profile set to other services. This command was working correctly up until recently. My IAM user in the aws account has administrator permissions set.

I have ran ask configure and configured it to the default account, and the command runs with no errors. I have uninstalled and reinstalled the ask-cli module multiple times as well.

**CLI Snapshot**
<img width="1420" alt="Screen Shot 2022-03-04 at 2 29 59 PM" src="https://user-images.githubusercontent.com/76024621/156837237-af34c98a-f70d-4b1d-b1b3-c0fabc5c62ec.png">

## Steps to Reproduce (for bugs)

$ `ask new` (or `ask new --profile default`)
? Choose the programming language you will use to code your skill:  NodeJS
? Choose a method to host your skill's backend resources:  AWS Lambda

```Error is returned```

## Your Environment and Context

* ask-cli version: 2.26.0
* Operating System and version: MacOS BigSur 11.5.1 (20G80)
* Node.js version used for development: v16.3.0
* NPM version used for development: 8.1.0

**Comment by tkm22** [comment] 2022-03-07 18:48
Thanks for letting us know! The issue has been identified. Our CLI templates store in S3 buckets, we changed access policy last week due to internal policy, that's why the templates cannot be access and threw 403 error. Now the access policy has been reverted back, and the issue is solved, so closing it now, and please let us know if you find anything else broken, thanks!

**Closed by tkm22** 2022-03-07 18:48 UTC

**Comment by rubenturcios** [comment] 2022-03-07 18:51
Thank you for the update!
