### ISSUE TITLE
option `--profile,-p` not respected

### ISSUE THREAD

**Issue by jessefarinacci** [alexa/ask-cli#178] opened 2020-05-09 14:09 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

No matter if I specify `-p` or `--profile` to the `ask` or `ask [subcmd]`, all variations ignore my requested profile. I have tried the profile named in `~/.ask/cli_config` but also out of paranoia the AWS credentials in `~/.aws/credentials` ... none of any of these configuration combinations works. Error message issued `[Error]: Cannot resolve profile [default]`

## Expected Behavior

Specifying `--profile myprofile` references the profile named `myprofile` found in `~/.ask/cli_config`.

## Current Behavior

Error message issued `[Error]: Cannot resolve profile [default]` and the command exits rc=1

**CLI Snapshot**
$ ask --version
2.6.0

## Steps to Reproduce (for bugs)

Create an ASK profile not named `default` and try to use it.

## Your Environment and Context

* ask-cli version: 2.6.0
* Operating System and version: MacOS 19.4.0
* Node.js version used for development: 14.0.0
* NPM version used for development: 6.14.5

**Comment by RonWang** [comment] 2020-05-11 17:15
Hi @jessefarinacci , this seems like a very strange issue that we might need your help to do some test in your machine...

Please first look at this [code](https://github.com/alexa/ask-cli/blob/develop/lib/utils/profile-helper.js#L34-L39), which is the logic that fails your command. You might need to create a test.js file with this code, and call this function with your desired profile. Use `node test.js` to test if the logic works. If the function doesn't pass, please forward the error message you see; if pass, we might need to further consider other approach to unblock.

Thanks for your cooperation over this,
Ron

**Comment by jessefarinacci** [comment] 2020-05-11 17:39
Sorry, I'm not sure I follow.. I'm a bit of a novice here. Wouldn't this be where the problem is? https://github.com/alexa/ask-cli/blob/develop/lib/utils/profile-helper.js#L15-L21 Because the error message indicates it is trying to lookup the `default` profile, which I do not have defined in `~/.ask/cli_config`.

Interestingly, when I invoke via `ASK_DEFAULT_PROFILE="myprofile" ask deploy` I get much further in the processing, so it at least appears to be finding that `myprofile` in that case.

**Comment by RonWang** [comment] 2020-05-11 23:52
Hey @jessefarinacci , because your error message shows `Cannot resolve profile [default]`, which is thrown because this [function](https://github.com/alexa/ask-cli/blob/develop/lib/utils/profile-helper.js#L33) returns false, that's why I wondered why it's false if you explicitly specify the cli command with `--profile`. If the profile name you specified exists in the cli_config, then that function should return true!

As you mentioned you don't have a default profile in cli_config, I've tried to reproduce, by removing the [default] profile from my cli_config, then try use the non-default profile directly. And it worked for me. It might be cli cannot read your cli_config file for some reason (might be encoding is not using 'utf-8'). That's why I need your help to try run that logic directly to diagnose, and then CLI can strengthen the case after the root cause discovered.

If the `ASK_DEFAULT_PROFILE` works, then it goes along the profile chain until it hits the non-empty value which is ASK_DEFAULT_PROFILE. Do you specify --profile when this env var works for you? If not then it's the correct behavior!

**Comment by jessefarinacci** [comment] 2020-05-12 12:39
I'm sorry, but I don't think so. Please look here the code https://github.com/alexa/ask-cli/blob/develop/lib/utils/profile-helper.js#L17-L18 invokes your `checkASKProfileExist` with the parameter `default` because the invoking method has no profile parameter and it gets all the way to the end of the line and sees the final `|| default` here https://github.com/alexa/ask-cli/blob/develop/lib/utils/profile-helper.js#L16 It then issues the warning message with the same variable that it passed to the lookup, `default`. Then checkASKProfileExist(default) returns false, because in my case I don't want any default ASK profile as I want to manage multiple profiles and be explicit about which one is doing the command.

Why do I set the `ASK_DEFAULT_PROFILE` variable? I was just testing the path and the processing of the method you said was in error. https://github.com/alexa/ask-cli/blob/develop/lib/utils/profile-helper.js#L16 to me indicates when I pass `--profile myprofile` it is not being chosen and goes all the way to the end with `|| default`; yet when I set `ASK_DEFAULT_PROFILE=myprofile` it is consumed and we never get to the `|| default` and so it is used in the checkASKProfileExist(myprofile) and the profile is found..

I don't know how to invoke the test you suggest, do I have to clone the repository and do craft a custom test.js using the code? I think that is beyond my skill at this point..

**Comment by RonWang** [comment] 2020-05-12 23:57
> https://github.com/alexa/ask-cli/blob/develop/lib/utils/profile-helper.js#L16 to me indicates when I pass `--profile myprofile` it is not being chosen and goes all the way to the end with `|| default`;

I think I figured [where the issue](https://github.com/alexa/ask-cli/blob/develop/lib/commands/abstract-command.js#L96) is! The profile is not passed in correctly. I will send a PR to fix this issue. Thanks for your reporting!!!

**Comment by jessefarinacci** [comment] 2020-05-13 01:59
Way to go @RonWang, that was a tricky one. :-) Nice! Thank you.

**Comment by kakhaUrigashvili** [comment] 2020-05-14 15:08
@jessefarinacci fixed in 2.7.0

**Closed by kakhaUrigashvili** 2020-05-14 15:08 UTC
Labels: Status: Next Release
