### ISSUE TITLE
git push leads to "TypeError: cb is not a function"

### ISSUE THREAD

**Issue by ndotmdot** [alexa/ask-cli#128] opened 2020-04-16 15:46 UTC
## I'm submitting a...
<pre><code>[x] Bug report</code></pre>

Might be related to [#116](https://github.com/alexa/ask-cli/issues/116)

## Expected Behavior
Using `git push` without error

## Current Behavior
When i try to push a hosted skill to any git branch i get the following error

**CLI Snapshot**

```
$ git push
/usr/local/lib/node_modules/ask-cli/lib/commands/util/git-credentials-helper/index.js:68
            cb();
            ^

TypeError: cb is not a function
    at /usr/local/lib/node_modules/ask-cli/lib/commands/util/git-credentials-helper/index.js:68:13
    at /usr/local/lib/node_modules/ask-cli/lib/clients/smapi-client/index.js:167:21
    at _normalizeSmapiResponse (/usr/local/lib/node_modules/ask-cli/lib/clients/smapi-client/index.js:187:5)
    at /usr/local/lib/node_modules/ask-cli/lib/clients/smapi-client/index.js:166:17
    at Request._callback (/usr/local/lib/node_modules/ask-cli/lib/clients/http-client.js:62:16)
    at Request.self.callback (/usr/local/lib/node_modules/ask-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.<anonymous> (/usr/local/lib/node_modules/ask-cli/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
/usr/local/lib/node_modules/ask-cli/lib/commands/util/git-credentials-helper/index.js:68
            cb();
            ^

TypeError: cb is not a function
    at /usr/local/lib/node_modules/ask-cli/lib/commands/util/git-credentials-helper/index.js:68:13
    at /usr/local/lib/node_modules/ask-cli/lib/clients/smapi-client/index.js:167:21
    at _normalizeSmapiResponse (/usr/local/lib/node_modules/ask-cli/lib/clients/smapi-client/index.js:187:5)
    at /usr/local/lib/node_modules/ask-cli/lib/clients/smapi-client/index.js:166:17
    at Request._callback (/usr/local/lib/node_modules/ask-cli/lib/clients/http-client.js:62:16)
    at Request.self.callback (/usr/local/lib/node_modules/ask-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.<anonymous> (/usr/local/lib/node_modules/ask-cli/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
```

## Steps to Reproduce
1. Create a new Skill in the alexa developer console
2. Clone repo with `ask init --hosted-skill-id <hosted-skill-id>`
3. Make Changes 
4. `git add .`
5. `git commit -m "msg"`
6. `git push`

## Environment
* ask-cli version: 2.1.0
* Operating System and version: OSX 10.15.3
* Node.js version used for development: 12.16.2

**Comment by RonWang** [comment] 2020-04-16 18:03
Hey @ndotmdot we are work on the fix for this issue. It's introduced in v2.1.0, so if the feature (https://github.com/alexa/ask-cli/blob/develop/CHANGELOG.md#210-2020-04-16) in this version is not influencing your work, please consider switch to v2.0.1 just for now. Sorry for the inconvenience and thanks for reporting!

**Comment by RonWang** [comment] 2020-04-16 21:37
The root cause of this issue is current CLI doesn't handle unparsed user input for a command. 

When reproducing this issue with `$ GIT_TRACE_SETUP=true GIT_TRACE=true git push`, I noticed git is attempting to get the git credentials by calling `ask util git-credentials-helper --profile default get`. 

However, since the trailing "get" is not recognized with current CLI's command definition in the CommanderJS, the [spread-ed "args" object](https://github.com/alexa/ask-cli/blob/develop/lib/commands/abstract-command.js#L103) pushes the "cb" to the 3rd parameter.

We will work on the fix for this issue.

**Closed** 2020-04-17 21:38 UTC
Labels: Priority: Critical, Reason: Commander Usage, Status: In Progress
