### ISSUE TITLE
Issue with ask new command

### ISSUE THREAD

**Issue by nwross95** [alexa/ask-cli#231] opened 2020-06-11 19:07 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

When I run the ask new command I get an error saying "Fatal error: too many arguments"

## Current Behavior

fatal: Too many arguments.

usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recurse-submodules[=<pathspec>]
                          initialize submodules in the clone
    --recursive ...       alias of --recurse-submodules
    -j, --jobs <n>        number of submodules cloned in parallel
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    --reference-if-able <repo>
                          reference repository
    --dissociate          use --reference only while cloning
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --shallow-since <time>
                          create a shallow clone since a specific time
    --shallow-exclude <revision>
                          deepen history of shallow clone, excluding rev
    --single-branch       clone only one branch, HEAD or --branch
    --no-tags             don't clone any tags, and make later fetches not to follow them
    --shallow-submodules  any cloned submodules will be shallow
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository
    --server-option <server-specific>
                          option to transmit
    -4, --ipv4            use IPv4 addresses only
    -6, --ipv6            use IPv6 addresses only
    --filter <args>       object filtering
    --remote-submodules   any cloned submodules will use their remote-tracking branch
    --sparse              initialize sparse-checkout file to include only files at root

[Error]: CliError: Error: Command failed: git clone --branch ask-cli-x https://github.com/alexa/skill-sample-nodejs-hello-world.git C:\Users\Nathan\Desktop\Python Projects\Warzone Assistant\Warzone

-------------------- Debug Mode --------------------
[2020-06-10T00:00:17.418Z] - DEBUG - GET_NPM_REGISTRY
GET http://registry.npmjs.org/ask-cli/latest
status code: 200 OK

Request headers: {"User-Agent":"ask-cli/2.10.1 Node/v12.8.0 Windows_NT/10.0.18363"}

Response headers: {"date":"Wed, 10 Jun 2020 00:00:17 GMT","content-type":"application/json","transfer-encoding":"chunked","connection":"close","set-cookie":["__cfduid=d2d34e68357e10b427655e331be09360e1591747216; expires=Fri, 10-Jul-20 00:00:16 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax"],"cf-ray":"5a0ecfaa1ce9ec62-DFW","vary":"Accept-Encoding","cf-cache-status":"DYNAMIC","cf-request-id":"033d201e4c0000ec627a929200000001","expect-ct":"max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"","server":"cloudflare"}

Response body: "{\"name\":\"ask-cli\",\"version\":\"2.10.1\",\"description\":\"Alexa Skills Kit (ASK) Command Line Interfaces\",\"bin\":{\"ask\":\"bin/ask.js\"},\"engines\":{\"node\":\">=8.3.0\"},\"license\":\"Apache 2.0\",\"repository\":{\"type\":\"git\",\"url\":\"git+https://github.com/alexa/ask-cli.git\"},\"author\":{\"name\":\"RonWang\",\"email\":\"nongwang@amazon.com\"},\"keywords\":[\"alexa\",\"skill\",\"cli\",\"package\",\"cloudformation\",\"serverless\",\"deploy\"],\"scripts\":{\"test\":\"node ./node_modules/mocha/bin/_mocha -u exports -R spec test/unit/run-test.js\",\"test:watch\":\"node ./node_modules/mocha/bin/_mocha
test/unit/run-test.js -w\",\"test:report\":\"nyc --cache npm test && nyc report --reporter=html\",\"test:browser\":\"npm run test:report && open coverage/index.html\",\"integration-test\":\"mocha -t 180000 test/integration/run-test.js\",\"functional-test\":\"mocha -t 180000 test/functional/run-test.js\",\"lint\":\"eslint lib/builtins lib/clients lib/commands lib/controllers lib/model lib/view\",\"pre-release\":\"standard-version\",\"prism\":\"prism\"},\"dependencies\":{\"adm-zip\":\"^0.4.13\",\"archiver\":\"^1.1.0\",\"ask-smapi-model\":\"1.9.3\",\"ask-smapi-sdk\":\"^1.2.0\",\"async\":\"^2.1.5\",\"aws-profile-handler\":\"2.0.3\",\"aws-sdk\":\"^2.288.0\",\"axios\":\"^0.19.2\",\"bunyan\":\"^1.8.12\",\"chalk\":\"2.4.2\",\"commander\":\"^4.1.1\",\"date-fns\":\"^2.7.0\",\"folder-hash\":\"^3.0.0\",\"fs-extra\":\"^2.1.0\",\"inquirer\":\"^6.2.0\",\"js-yaml\":\"^3.13.1\",\"jsonfile\":\"^2.4.0\",\"listr\":\"^0.14.3\",\"module-alias\":\"^2.1.0\",\"mustache\":\"^4.0.1\",\"open\":\"^7.0.3\",\"ora\":\"^3.4.0\",\"portscanner\":\"^2.1.1\",\"pretty-bytes\":\"^5.1.0\",\"ramda\":\"^0.27.0\",\"request\":\"^2.79.0\",\"rxjs\":\"^6.5.2\",\"semver\":\"^5.3.0\",\"shelljs\":\"^0.8.2\",\"simple-git\":\"^1.82.0\",\"tmp\":\"^0.1.0\",\"uuid\":\"^3.4.0\",\"valid-url\":\"^1.0.9\"},\"devDependencies\":{\"@commitlint/cli\":\"^8.2.0\",\"@commitlint/config-conventional\":\"^8.2.0\",\"@stoplight/prism-cli\":\"^3.3.3\",\"chai\":\"^3.5.0\",\"chai-json-schema\":\"^1.5.1\",\"chai-uuid\":\"^1.0.6\",\"coveralls\":\"^3.0.2\",\"eslint\":\"^6.8.0\",\"eslint-config-airbnb-base\":\"^14.0.0\",\"eslint-plugin-import\":\"^2.20.1\",\"gulp\":\"^3.9.1\",\"husky\":\"^4.2.3\",\"mocha\":\"^3.2.0\",\"mocha.parallel\":\"^0.15.6\",\"nyc\":\"^13.3.0\",\"proxyquire\":\"^1.7.11\",\"sinon\":\"^6.0.0\",\"standard-version\":\"^7.0.0\"},\"husky\":{\"hooks\":{\"pre-commit\":\"npm run lint\",\"commit-msg\":\"commitlint -E HUSKY_GIT_PARAMS\",\"pre-push\":\"npm run test:report\"}},\"nyc\":{\"check-coverage\":true,\"lines\":95,\"statements\":95,\"functions\":95,\"branches\":95,\"include\":[\"lib/utils/string-utils.js\",\"lib/utils/url-utils.js\",\"lib/utils/zip-utils.js\",\"lib/utils/hash-utils.js\",\"lib/utils/retry-utility.js\",\"lib/builtins/*\",\"lib/clients/*\",\"lib/model/*\",\"lib/view/*\",\"lib/controllers/*\",\"lib/commands/*\"],\"exclude\":[\"lib/clients/aws-client/aws-util.js\"]},\"_moduleAliases\":{\"@root\":\".\",\"@src\":\"./lib\",\"@test\":\"./test\"},\"gitHead\":\"3a3fb4fed910bc66154664771f9ee8b7ae60f4cc\",\"bugs\":{\"url\":\"https://github.com/alexa/ask-cli/issues\"},\"homepage\":\"https://github.com/alexa/ask-cli#readme\",\"_id\":\"ask-cli@2.10.1\",\"_npmVersion\":\"6.4.1\",\"_nodeVersion\":\"11.4.0\",\"_npmUser\":{\"name\":\"ask-dev-tools\",\"email\":\"ask-tools@amazon.com\"},\"dist\":{\"integrity\":\"sha512-wPsd/kHrlrvfcQXsep+ZOUQ4CRYHL/NMVUxoJPpmO3ZCcJZXpdMmZ3N2hAEIN63eMtX5RYecyAYeUCIdpnQnoQ==\",\"shasum\":\"24435b1ba503693f851e1e3f401149ee82085044\",\"tarball\":\"https://registry.npmjs.org/ask-cli/-/ask-cli-2.10.1.tgz\",\"fileCount\":301,\"unpackedSize\":2014178,\"npm-signature\":\"-----BEGIN PGP SIGNATURE-----\\r\\nVersion: OpenPGP.js v3.0.4\\r\\nComment: https://openpgpjs.org\\r\\n\\r\\nwsFcBAEBCAAQBQJe2qpGCRA9TVsSAnZWagAAluAP/1CugAShEB+c/XhJv9g5\\n8p/j+r/6wzmlIqey8ikf6zFIAlYSX/FemUQZLGUFAEepsC029L1X03WNJLAn\\notCvf6fGiLq1YyHKhvXp4rgzLJwfjRf8GRXJ1C2pSmORWp+1nj80ZmE4DE4G\\n+EpoJK4hOF12DvFQHUQqjtzJ3I7MqArT9NjHHrq4BXodMuI8YxtOpBrVs7Kd\\nFJ+RYrGhWpvCxFUwdHGj48RtNVV9mEgfRhv+ZCEpf/cyC75dro0yGXJThL42\\nOBYedkC5RdbZpGJadQ+eDic1ugslLUi7a1Lar0NTndaxYFyi622OcC0jOi0L\\n8XV1kG82lb8w9OfSeYrYTPzHPYOyfemuJ0kPgVrKnzEohrKRGwkkbjuvj7lY\\nU5eH+e6EhUQGX2YLWr2F0CwGpxiaoph4NhvPJsEQb4ebbM4LgWBMkB2EfJVc\\nuhl2jobdKeYU/w35TuSP5G0PCRpdxwRRYm7ki2KWTPgMVt/8AvXHaED1jAVT\\nAd9tha1EY8M/3eAkQ/7ecJ4MhDtPkKhdPUbRzh7Aony5E4/WVf5VeFOFpVWq\\nINShn7OUZeOGkyhPAIWXfEjFBmhILS+7Fl3mheGQCDO7UZrM/V+o3Dwzmq94\\nugWGytiqSrOsFC8HLCtLllikWkg4U/02VY+dL1aPKbaUonCMQj/5oeEYQ+hq\\nvoJy\\r\\n=ujdY\\r\\n-----END PGP SIGNATURE-----\\r\\n\"},\"maintainers\":[{\"name\":\"ask-dev-tools\",\"email\":\"ask-cli@amazon.com\"}],\"directories\":{},\"_npmOperationalInternal\":{\"host\":\"s3://npm-registry-packages\",\"tmp\":\"tmp/ask-cli_2.10.1_1591388741418_0.3013043717549593\"},\"_hasShrinkwrap\":false}"
----------------------------------------
[2020-06-10T00:00:20.706Z] - DEBUG - GETTEMPLATESMAP
GET https://ask-cli-static-content.s3-us-west-2.amazonaws.com/skill-templates/NodeJS/lambda-deployer-templates.json
status code: 200 OK

Request headers: {"User-Agent":"ask-cli/2.10.1 Node/v12.8.0 Windows_NT/10.0.18363"}

Response headers: {"x-amz-id-2":"RNy86UoM8YD2QHci2fPFn7GgYinMGVAWCOBjuO4VZ+RlxIpmVv/8EM5u/1zTZ9/Si/Kng3YsBJo=","x-amz-request-id":"CE14E0326270A6AD","date":"Wed, 10 Jun 2020 00:00:21 GMT","last-modified":"Wed, 01 Apr 2020 22:16:06 GMT","etag":"\"c6aa673607af89a2b73b48fa6e81fb9d\"","x-amz-version-id":"iGiLBv2iPS7zvpvDk2sgTn.5fuwoFb2M","accept-ranges":"bytes","content-type":"application/json","content-length":"378","server":"AmazonS3","connection":"close"}

Response body: "{\n    \"Hello world\": {\n        \"url\": \"https://github.com/alexa/skill-sample-nodejs-hello-world.git\",\n        \"description\": \"Alexa's hello world skill to send the greetings to the world!\"\n    },\n    \"Fact skill\": {\n        \"url\": \"https://github.com/alexa/skill-sample-nodejs-fact.git\",\n        \"description\": \"Quick sample skill to manage a collection of voice data.\"\n    }\n}\n"

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: 2.10.1
* Operating System and version: Windows 10
* Node.js version used for development: 6.10.2
* NPM version used for development: 12.8.0

**Comment by kakhaUrigashvili** [comment] 2020-06-11 22:09
@nwross95 Thank you for reporting the issue. it is caused by space in the path. I will take look into fixing this.

**Comment by kakhaUrigashvili** [comment] 2020-06-11 22:36
@nwross95 fixed in 2.10.2

**Closed by kakhaUrigashvili** 2020-06-11 22:36 UTC
