### ISSUE TITLE
Multi-Capability Skills

### ISSUE THREAD

**Issue by fredolphin** [alexa/ask-cli#212] opened 2020-05-28 22:17 UTC
Hello,

Does this version of ask cli support Multi-Capability Skills released generally today ? 

Step 1: I have updated my skill using the Console. 

Step 2:  Then I sync it back locally using : 
ask smapi export-package --skill-id <skill_id> --stage development

Step 3: Then I try to deploy it again using : ask deploy
I got the following errors:
_[Error]: {
  "message": "Skill manifest is not valid.",
  "violations": [
    {
      "code": "INVALID_URL_FORMAT",
      "message": "String instance with value \"file://assets/images/fr-FR_largeIconUri.png\" at property path \"$.manifest.publishingInformation.locales.fr-FR.largeIconUri\" is not a valid URL.",
      "validationDetails": {
        "originalInstance": {
          "dataType": "string",
          "propertyPath": "$.manifest.publishingInformation.locales.fr-FR.largeIconUri",
          "type": "BODY",
          "value": "file://assets/images/fr-FR_largeIconUri.png"
        }
      }
    },
    {
      "code": "INVALID_URL_FORMAT",
      "message": "String instance with value \"file://assets/images/fr-FR_smallIconUri.png\" at property path \"$.manifest.publishingInformation.locales.fr-FR.smallIconUri\" is not a valid URL.",
      "validationDetails": {
        "originalInstance": {
          "dataType": "string",
          "propertyPath": "$.manifest.publishingInformation.locales.fr-FR.smallIconUri",
          "type": "BODY",
          "value": "file://assets/images/fr-FR_smallIconUri.png"
        }
      }
    }
  ]
}_

Thank you for your light.

Regards,
Frédéric

**Comment by kakhaUrigashvili** [comment] 2020-05-29 03:00
@fredolphin Thank you for reporting the issue. I was not able to reproduce it. The error message comes directly from smapi api.

Are you able to provide more details to help reproduce it?

**Comment by RonWang** [comment] 2020-05-29 03:31
Hey @fredolphin also seems the error message from SMAPI is saying :
> "message": "String instance with value "file://assets/images/fr-FR_largeIconUri.png" at property path "$.manifest.publishingInformation.locales.fr-FR.largeIconUri" is not a valid URL."

Could you check your skill.json in the skill-package if the value is set correctly?

**Comment by fredolphin** [comment] 2020-05-29 18:16
Hello,

I finally workaround it by setting real URL after uploading my images in S3.
However, I got the following error when executing ask deploy:
==================== Enable Skill ====================
[Error]: CliError: [Warn]: Skill with multiple api domains cannot be enabled. Skip the enable process.

When I remove the custom section in the "apis" JSON section, I got the following error:
==================== Enable Skill ====================
[Error]: CliError: [Warn]: Skill api domain "smartHome" cannot be enabled. Skip the enable process.

Would you know why ? 

Thank you
Frédéric

**Comment by kakhaUrigashvili** [comment] 2020-05-29 20:38
@fredolphin looks like it is not supported


https://github.com/alexa/ask-cli/blob/develop/lib/controllers/skill-metadata-controller/index.js#L83

https://github.com/alexa/ask-cli/blob/develop/lib/utils/constants.js#L117

**Comment by kakhaUrigashvili** [comment] 2020-06-01 15:54
@fredolphin I will talk to the team about it this week and we will get back to you.

**Comment by RonWang** [comment] 2020-06-29 20:55
Hi @fredolphin 

As you may know smartHome skill is relying on the account linking heavily. A smartHome skill cannot be enabled if it doesn't have account linking set. For those types of skills which require account linking information, CLI doesn't enable by default because CLI cannot check the validity of account linking, as well as our upstream API also doesn't support it. 

Will close this issue as this is business decision from our backend as well, hope the reason makes sense to you. Please let us know if you feel strongly that you need this support by reopening the issue.

Thanks,
Ron

**Closed by RonWang** 2020-06-29 20:55 UTC
Labels: Status: Wait Response
